### ISSUE TITLE
Amazing Mod!

### ISSUE THREAD

**Issue by DaSk79130569** [sultim-t/Serious-Engine-RT#12]
This is absolutely amazing work! Works perfectly on my Geforce 3080 Ti (with bloom turned off). The community really appreciates all of your hard work and effort!

I was wondering is there any way you may have interest in tackling Deus Ex 1 with full ray-tracing (Unreal engine)?

**Comment by sultim-t** [comment]
Thanks, but Unreal 1 is not open aourced 🙂

**Comment by Calinou** [comment]
> Thanks, but Unreal 1 is not open aourced slightly_smiling_face

While Unreal Engine 1 is not open source, it *is* possible to write custom rendering backends thanks to its DLL-based renderer system. This is similar to Quake 2 where it was possible to write custom renderers for it before it was open sourced. See https://github.com/mkentie/render12 and https://github.com/mkentie/render11 for examples of this.

(Note: I'm not requesting that you write this renderer, I'm just leaving this information out there for completeness.)
