### ISSUE TITLE
Mod compatibility with Serious Sam Classics Revolution

### ISSUE THREAD

**Issue by maximus105** [sultim-t/Serious-Engine-RT#14]
Please add mod compatibility with Serious Sam Classics Revolution.
Serious Sam Classics: Revolution is a combined version of the original Serious Sam Classic: The First Encounter and Serious Sam Classic: The Second Encounter. The hybrid is built on a heavily modified Serious Engine 1. From now on, the engine has extended support for graphics shaders and full compatibility with 64-bit operating systems. On top of all that, Serious Sam Classics: Revolution includes additional enemies and 8 brand new campaign maps, including an epic new boss.

**Comment by LethalManBoob** [comment]
While in theory this is a good idea, the massive overhalls to the engine would probably mean a lot of work to port something like RT over. Seeing as even TSE isn't on the cards yet, revolution is certainly out as well.

**Comment by sultim-t** [comment]
Revolution is not open sourced, so can't do anything :/
