### ISSUE TITLE
DLSS feature is missing even with the nvngx_dlss.dll + Music is missing?

### ISSUE THREAD

**Issue by JG-Adams** [sultim-t/Serious-Engine-RT#15]
I'm using 3070 RTX.
I place this file, nvngx_dlss.dll,  into the Bin/
However this feature is still disabled?

My situation:
I have a CD version of the game that only had:
1_00.gro
1_00_ExtraTools.gro
1_00_music.gro

I didn't see any of the:
1_00c_Logo.gro
1_00c_scripts.gro
1_04_patch.gro

Could this be the cause? It runs anyway. Nice Mod!
I would appreciate the help. It's my first RTX Game on a tryout!

===================

I also experience a lack of music in game. :(

**Comment by sultim-t** [comment]
Not sure, but It might be the engine version collision, the open souce one is 1.10 and I was only testing it with Steam files.

**Comment by JG-Adams** [comment]
Thank for responding!
I forgot to mention that I'm running on window 7. (Mainly because I don't like 8, 10, or 11)
Would it be possible to pass these 6 particular files? Kinda curious to try DLSS

**Comment by JG-Adams** [comment]
I upgraded to window 10 now.
The missing music and dlss still persist. But a bunch of things were fixed I hadn't mention. I'll place another post on that.

**Comment by JG-Adams** [comment]
I bought the Gog version of the game.
It came with the files and it works.
Other things I notice is that the visual quality is better too!
(Specular lighting was real noisy in dark area. Maybe denoising wasn't working)
However, I'm still not getting dlss option.

**Comment by Strelok111** [comment]
yeah the issue still exists
rtx 3070
i7 12th gen
32gb of ram
windows 10

**Comment by JG-Adams** [comment]
Hey guys! The new version seems to fix it!
The RayTracedGL1-DLSS.zip file made it work.

The CD issue may not be a big deal, but it's nice to support it.
