### ISSUE TITLE
Certain File missing?

### ISSUE THREAD

**Issue by theholyarcher** [sultim-t/Serious-Engine-RT#4]
For some reason when I tried to start the game it said that ArStrong.tex is missing. I looked in the textures and sure enough, it's not there. Is this a download issue or?

**Comment by ds64** [comment]
I had the same error when I didn't put .gro files in the game folder. You need to get these files from either Steam or GOG version of the game.

**Comment by theholyarcher** [comment]
> I had the same error when I didn't put .gro files in the game folder. You need to get these files from either Steam or GOG version of the game.

I actually got the .gro files but I could've put them in the wrong place, is there somewhere specific they need to be put?

**Comment by sultim-t** [comment]
Read the Readme file very carefully  https://github.com/sultim-t/Serious-Engine-RT/releases

Maybe you're missing `SE1_10.gro` from `TFE_RT_Bin.zip`
